name: Spider Jar Gen CI

on:
  push:
    branches: [ "multiThread" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'jetbrains'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew app:buildCustomSpiderJar


      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: 'update spider jar and json'
          add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5','./json/index.json']"

      - name: upload json
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: mseet_40633048
          # ftp password
          password: ${{ secrets.FTP_PWD }}
          # Server port to connect to (read your web hosts docs)
          port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp
          # Folder to upload from, must end with trailing slash /
          local-dir: ${{ github.workspace }}/json/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: htdocs/json/
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          dangerous-clean-slate: true
          exclude: |
            **/js/**

      - name: upload jar
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: ${{ secrets.FTP_PWD }}
          # ftp password
          password: DL0NzRdjf1Wv
          # Server port to connect to (read your web hosts docs)
          port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp
          # Folder to upload from, must end with trailing slash /
          local-dir: ${{ github.workspace }}/jar/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: htdocs/jar/
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          dangerous-clean-slate: true





